In [1]:
#Initial imports
import requests
import pandas as pd
import numpy as np
import datetime as dt
import os
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi
import json

In [2]:
#Load API keys file
load_dotenv("OUR_KEYS.env")

True

In [3]:
#Set Crypto Compare API keys for crypto data
cryptocompare_api_key = os.getenv("CRYPTOCOMPARE_API_KEY")
type(cryptocompare_api_key)

str

In [5]:
#Set Alpaca API keys for US stock market data
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")
type(alpaca_api_key)
type(alpaca_secret_key)

str

In [6]:
#Create the Alpaca API object
alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version="v2")

In [7]:
#Set the tickers to include the S&P500, ARK Innovation, and NASDAQ-100 
tickers = ["SPY", "ARKK", "QQQ"]

#Set the timeframe for data
timeframe = "1D"

#Set the start & end dates
start_date = pd.Timestamp("2017-01-01", tz="America/New_York").isoformat()
end_date = pd.Timestamp("today").isoformat()

In [8]:
#Request the stock data from Alpaca
stock_data_df = alpaca.get_barset(
    tickers,
    timeframe,
    start = start_date,
    end = end_date,
    limit=1000
).df

stock_data_df

                             ARKK                                        QQQ  \
                             open     high      low   close   volume    open
time
2017-11-24 00:00:00-05:00   36.93   37.030   36.797   36.88   222437  155.86
2017-11-27 00:00:00-05:00   37.14   37.410   37.010   37.25   287691  156.20
2017-11-28 00:00:00-05:00   37.45   37.750   37.340   37.66   407482  156.52
2017-11-29 00:00:00-05:00   37.94   38.200   36.510   36.98   327319  156.42
2017-11-30 00:00:00-05:00   37.08   37.385   36.651   37.22   238721  154.46
...                           ...      ...      ...     ...      ...     ...
2021-11-08 00:00:00-05:00  121.69  124.300  121.610  123.40  3266167  398.57
2021-11-09 00:00:00-05:00  123.91  124.220  119.650  120.50  5570377  399.16
2021-11-10 00:00:00-05:00  118.44  120.785  115.200  116.65  7568712  392.47
2021-11-11 00:00:00-05:00  118.28  118.780  117.100  117.24  3826637  392.57
2021-11-12 00:00:00-05:00  117.77  118.520  116.710  118.50  3522223  391.77

                                                                 SPY          \
                             high      low   close    volume    open    high
time
2017-11-24 00:00:00-05:00  156.31  155.760  156.25   5770066  260.28  260.48
2017-11-27 00:00:00-05:00  156.56  155.830  156.19  15156409  260.41  260.75
2017-11-28 00:00:00-05:00  156.69  155.700  156.61  17431023  260.76  262.90
2017-11-29 00:00:00-05:00  156.45  153.120  153.88  57811175  263.02  263.63
2017-11-30 00:00:00-05:00  155.45  154.145  155.15  44193400  263.76  266.05
...                           ...      ...     ...       ...     ...     ...
2021-11-08 00:00:00-05:00  399.62  397.400  398.06  26737662  469.70  470.23
2021-11-09 00:00:00-05:00  399.57  393.920  395.28  48114670  469.32  469.57
2021-11-10 00:00:00-05:00  395.36  387.530  389.49  49753283  465.58  467.38
2021-11-11 00:00:00-05:00  392.75  390.240  390.62  28990905  465.21  465.29
2021-11-12 00:00:00-05:00  395.25  390.130  394.72  30500126  465.12  467.86


                                low   close    volume
time
2017-11-24 00:00:00-05:00  260.1600  260.34  16323543
2017-11-27 00:00:00-05:00  260.0000  260.26  29732937
2017-11-28 00:00:00-05:00  258.4000  262.85  57806500
2017-11-29 00:00:00-05:00  262.2000  262.73  51230764
2017-11-30 00:00:00-05:00  263.6700  264.88  82186751
...                             ...     ...       ...
2021-11-08 00:00:00-05:00  468.2031  468.97  38945705
2021-11-09 00:00:00-05:00  465.8800  467.38  47198095
2021-11-10 00:00:00-05:00  462.0400  463.63  63500032
2021-11-11 00:00:00-05:00  463.7500  463.81  31757893
2021-11-12 00:00:00-05:00  464.1100  467.26  44677612

[1000 rows x 15 columns]

In [9]:
#Create Ethereum API URL
eth_url = "https://min-api.cryptocompare.com/data/v2/histoday?fsym=ETH&tsym=USD&limit=2000"

In [10]:
#Request historical Ethereum data from Crypto Compare
eth_response_data = requests.get(eth_url).json()

#print(json.dumps([eth_response_data], indent=4))